source "https://rubygems.org"
ruby "3.2.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.7"
gem "rack-cors"
gem "active_model_serializers", "~> 0.10"

group :development, :test do
  gem "dotenv-rails"
end
